version: '3.8'
services:
  redmine-db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - ./data/db2:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redmine:
    image: redmine:passenger
    container_name: redmine
    ports:
      - 80:3000
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_ENCODING: utf8mb4
    depends_on:
      - redmine-db
    restart: always
    volumes:
      - ./data/plugins:/usr/src/redmine/plugins
      - ./data/files:/usr/src/redmine/files
      - ./data/log:/usr/src/redmine/log
      - ./data/themes:/usr/src/redmine/public/themes
